routes/web.php
            //     'Admin\PermintaanPengujianTestSampleController',
            //     [
            //         'as' => 'admin.permintaan-pengujian',
            //     ]
            // );

            // Route::get(
            //     '/admin/permintaan-pengujian/{pengujian}',
            //     'PermintaanPengujian@show'
            // )
            // ->name('admin.permintaan.show');
            // Route::get(
            //     '/admin/permintaan-pengujian/{id}/status/diterima',
            //     'PermintaanPengujian@terimaPermintaan'
            // )->name('admin.permintaan.diterima');
            // Route::get(
            //     '/admin/permintaan-pengujian/{id}/status/ditolak',
            //     'PermintaanPengujian@tolakPermintaan'
            // )->name('admin.permintaan.ditolak');
            // Route::get(
            //     '/admin/permintaan-pengujian/{id}/status/selesai',
            //     'PermintaanPengujian@selesaiPermintaan'
            // )->name('admin.permintaan.selesai');
            // Route::get(
            //     '/admin/permintaan-pengujian',
            //     'PermintaanPengujian@index'
            // )->name('admin.permintaan.index');

            // .Permintaan Pelayanan

            Route::resource('/admin/pejabat', 'PejabatController');

            Route::resource('/admin/pengajar', 'PengajarController');

            Route::resource('/admin/galeri', 'GaleriController');
            Route::get('/admin/galerivideo/create', 'GaleriController@createVideo')->name('galeri.createVideo');
            Route::get('/admin/galerivideo/{$id}/edit', 'GaleriController@editVideo')->name('galeri.editVideo');

            Route::get(
                '/admin/peralatan/barcode/{alat}',
                'PeralatanLabController@showBarcode'
            )->name('peralatan.barcode');

            Route::group(['prefix' => '/admin'], function () {
                Route::get('/get-peralatan-by-name', 'PeralatanLabController@getPeralatanByName')
                    ->name('admin.peralatan.get-peralatan-by-name');
                Route::get('/get-peralatan-by-id', 'PeralatanLabController@getPeralatanById')
                    ->name('admin.peralatan.get-peralatan-by-id');
                Route::resource('/peralatan', 'PeralatanLabController', [
                    'as' => 'admin',
                ]);
                Route::resource('/peralatan/{peralatan}/calibration', 'Admin\PeralatanKalibrasiController', [
                    'as' => 'admin',
                ]);
                Route::resource('/peralatan/usage', 'Admin\PeralatanLabUsageController', [
                    'as' => 'admin',
                ]);
                Route::get('/peralatan/{peralatan}/usage', 'Admin\PeralatanLabUsageController@index')
                    ->name('admin.usage.index');
            });

            Route::resource('/admin/lab', 'LabController');

            Route::resource('/admin/fasilitas', 'SaranaPrasaranaController');

            // Slider
            Route::resource('/admin/slider', 'SliderController');

            Route::resource('/admin/client', 'Admin\ClientController', [
                'as' => 'admin',
            ]);

            Route::resource('/admin/pekerjaan', 'PekerjaanController');

            // Pegawai
            Route::resource('/admin/pegawai/jabatan-laboratorium', 'Admin\LabPositionController', [
                'as' => 'admin.pegawai',
            ]);
            Route::resource('/admin/pegawai/jabatan', 'Admin\JabatanController', [
                'as' => 'admin.pegawai',
            ]);
            Route::resource('/jadwal-kegiatan-personil', 'Admin\JadwalKegiatanPersonilController', [
                'as' => 'admin.pegawai',
            ]);
            Route::resource('/admin/pegawai/golongan', 'Admin\GolonganController', [
                'as' => 'admin.pegawai',
            ]);
            Route::get(
                '/admin/pegawai/get-jabatan-laboratorium',
                'Admin\PegawaiController@getLaboratoriumPositions'
            )
            ->name('admin.pegawai.get-jabatan-laboratorium');
            Route::get(
                '/admin/pegawai/get-jabatan-fungsional',
                'Admin\PegawaiController@getFunctionalPositions'
            )
            ->name('admin.pegawai.get-jabatan-fungsional');
            Route::resource('/admin/pegawai', 'Admin\PegawaiController', [
                'as' => 'admin',
            ]);

            Route::resource('/admin/akun', 'Admin\AkunController', [
                'as' => 'admin',
            ]);

            Route::resource('/admin/roles', 'Admin\RoleController', [
                'as' => 'admin',
            ]);
            Route::resource('/admin/products', 'Admin\ProductController', [
                'as' => 'admin',
            ]);
            Route::resource('/admin/kuisioners', 'Admin\KuisionerController', [
                'as' => 'admin',
            ]);

            Route::resource('/admin/indeks-kepuasan', 'IndeksKepuasanController');

            // Jadwal Pengujian
            Route::get(
                '/admin/jadwal-pengujian/{id}/status/dilaksanakan',
                'KegiatanController@statusDilaksanakan'
            )->name('jadwal-pengujian.status.dilaksanakan');
            Route::get(
                '/admin/jadwal-pengujian/{id}/status/tidak-dilaksanakan',
                'KegiatanController@statusTidakDilaksanakan'
            )->name('jadwal-pengujian.status.tidak');
            Route::get(
                '/admin/jadwal-pengujian/{id}/status/sedang-dilaksanakan',
                'KegiatanController@statusSedangDilaksanakan'
            )->name('jadwal-pengujian.status.sedang');
            Route::get(
                '/admin/jadwal-pengujian/{id}/status/selesai-dilaksanakan',
                'KegiatanController@statusSelesaiDilaksanakan'
            )->name('jadwal-pengujian.status.selesai');
            Route::resource('/admin/jadwal-pengujian', 'KegiatanController');

            // Jadwal Bimtek
            Route::get(
                '/admin/jadwal-bimtek/{id}/status/dilaksanakan',
                'JadwalBimtekController@statusDilaksanakan'
            )->name('jadwal-bimtek.status.dilaksanakan');
            Route::get(
                '/admin/jadwal-bimtek/{id}/status/tidak-dilaksanakan',
                'JadwalBimtekController@statusTidakDilaksanakan'
            )->name('jadwal-bimtek.status.tidak');
            Route::get(
                '/admin/jadwal-bimtek/{id}/status/sedang-dilaksanakan',
                'JadwalBimtekController@statusSedangDilaksanakan'
            )->name('jadwal-bimtek.status.sedang');
            Route::get(
                '/admin/jadwal-bimtek/{id}/status/selesai-dilaksanakan',
                'JadwalBimtekController@statusSelesaiDilaksanakan'
            )->name('jadwal-bimtek.status.selesai');
            Route::resource('/admin/jadwal-bimtek', 'JadwalBimtekController');

            Route::get('/admin/kepuasan-pelanggan', 'KepuasanPelangganController@index')->name('kepuasan-pelanggan.index');

            // Data Master
            Route::resource('/admin/master-pelayanan-uji', 'Admin\MasterLayananUjiController');
    });
});

Route::get(
    '/client/permintaan-pengujian/download',
    'V1\DownloadController@index'
)
->middleware(EnsureKuisionerFilled::class)
->name('permintaan-pengujian.download');
Route::get(
    '/client/permintaan-pengujian/{pengujian}/kuisioner',
    'V1\Client\PermintaanPengujianKuisionerController@index'
)
->name('permintaan-pengujian.kuisioner');

Route::group(
    [
        'middleware' => 'auth',
        'prefix' => 'client',
        'namespace' => 'V1\Client'
    ],
    function () {

        Route::group(['as' => 'client.'], function () {
            Route::resource('permintaan-pengujian', 'PermintaanPengujian');
            Route::get(
                'permintaan-pengujian/{permintaan_pengujian}/payment-confirmation',
                'PermintaanPengujian@paymentConfirmation'
            )->name('permintaan-pengujian.payment-confirmation.get');
            Route::post(
                'permintaan-pengujian/{permintaan_pengujian}/payment-confirmation',
                'PermintaanPengujian@paymentConfirmationPost'
            )->name('permintaan-pengujian.payment-confirmation.post');

            Route::resource(
                'permintaan-pengujian/{permintaan_pengujian}/test-sample',
                'PermintaanPengujianTestSampleController',
                [
                    'as' => 'permintaan-pengujian',
                ]
            );

            Route::get(
                'permintaan-pengujian/{permintaan_pengujian}/laporan-hasil-uji',
                'PermintaanPengujian@laporanHasilUji'
            )->name('permintaan-pengujian.laporan-hasil-uji.get');
        });

    // Client profile
        Route::get('/profile', 'ProfileController@index')->name('client.profile.index');
        Route::put('/profile/{user}', 'ProfileController@update')->name('client.profile.update');

        Route::get(
            '/bimtek',
            'BimtekClientsController@list'
        )->name('client.bimtek.list');

        Route::get(
            '/advisiteknis',
            'AdvisiTeknisController@index'
        )->name('client.advisiteknis.index');


        Route::get('/client/setting-client', 'ClientController@settingClient')->name('client.setting.index');
        Route::post(
            '/setting-client/store',
            'ClientController@settingClientUpdate'
        )->name('client.setting.store');

        Route::post('/password-reset', 'ClientController@password')->name('client.password.reset');

        Route::get('/umpan-balik', 'UmpanBalikController@create')->name('umpan-balik.index');
        Route::post('/umpan-balik/store', 'UmpanBalikController@store')->name('umpan-balik.store');

        Route::get(
            '/kepuasan-pelanggan/create',
            'KepuasanPelangganController@create'

resources/views/admin/lab-p/create.blade.php
@extends('layouts.adminlte')
@section('main')
<div class="container">
@if (session()->has('success'))
    <div class="alert alert-success" role="alert">
        {{ session()->get('success') }}
    </div>
@endif
@if (session()->has('failed'))
    <div class="alert alert-danger" role="alert">
        {{ session()->get('failed') }}
    </div>
@endif
    <div class="row h-100">
        <div class="col-md-12">
            <div class="card card-block d-flex">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="float-left">
                                <a href="{{ route('lab.index') }}" class="btn btn-primary btn-sm">kembali</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ route('lab.store') }}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-row">
                                            <div class="form-group col-md-12">
                                                <label>Foto <small class="text-success">*Harus diisi</small></label>
                                                <input type="file" name="foto" class="form-control-file @error('foto') is-invalid @enderror" aria-describedby="detail">
                                                <small id="detail" class="form-text text-danger">Tipe file image: JPG, JPEG, PNG; Max berukuran 2mb</small>
                                                @error('foto')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label>Nama Lab <small class="text-success">*Harus diisi</small></label>
                                                <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') }}">
                                                @error('nama')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label>Kategori <small class="text-success">*Harus diisi</small></label>
                                                <select name="kategori" class="form-control @error('kategori') is-invalid @enderror">
                                                    <option value="bahan">Lab Bahan</option>
                                                    <option value="struktur">Lab Struktur</option>
                                                </select>
                                                @error('kategori')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-row">
                                            <div class="form-group col-md-12">
                                                <label>Keterangan Lab <small class="text-success">*Harus diisi</small></label>
                                                <textarea class="form-control @error('keterangan') is-invalid @enderror" name="keterangan" rows="5">{{ old('keterangan') }}</textarea>
                                                @error('keterangan')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 mb-3" id="btnAdd">
                                        <div class="float-right">
                                            <button type="submit" class="btn btn-success btn-sm">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
{{-- Chart Section --}}
<script src="{{ asset('/adminlte/plugins/jquery/jquery.min.js') }}"></script>
<script type="text/javascript">

</script>
@endpush

resources/views/admin/lab-p/edit.blade.php
@extends('layouts.adminlte')
@section('main')
@include('admin.parts.breadcrumbs', [
	'judul' => [
        ['judul' => 'Data Lab',
		'link' => route('lab.index')],
        ['judul' => 'Ubah Data Lab']
    ]
])
<div class="container">
@if (session()->has('success'))
    <div class="alert alert-success" role="alert">
        {{ session()->get('success') }}
    </div>
@endif
@if (session()->has('failed'))
    <div class="alert alert-danger" role="alert">
        {{ session()->get('failed') }}
    </div>
@endif
    <div class="row h-100">
        <div class="col-md-12">
            <div class="card card-block d-flex">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="float-left">
                                Ubah Data Lab
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ route('lab.update', $data->id) }}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-row">
                                            <div class="form-group col-md-12">
                                                <label>Keterangan Lab <small class="text-success">*Harus diisi</small></label>
                                                <textarea class="form-control @error('keterangan') is-invalid @enderror" name="keterangan" rows="5">{{ $data->keterangan }}</textarea>
                                                @error('keterangan')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 mb-3" id="btnAdd">
                                        <div class="float-right">
                                            <button type="submit" class="btn btn-success btn-sm">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
{{-- Chart Section --}}
<script src="{{ asset('/adminlte/plugins/jquery/jquery.min.js') }}"></script>
<script type="text/javascript">

</script>
@endpush