routes/web.php
<?php

use App\Http\Middleware\EnsureKuisionerFilled;
use App\Mail\CobaMail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear', function () {

    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');

    return "Cleared!";
});
Route::get('/storage-link', function () {

    Artisan::call('storage:link');

    return "Storage Linked!";
});

Route::get('/update', function () {

    Artisan::call('migrate');
    Artisan::call('optimize:clear');

    return "Updated!";
});

Route::get('/update-permission', function () {

    Artisan::call('permission:create-permission "submit.advisi-teknis"');

    return "Permission Updated!";
});

// Homepage Route
Route::get('/', 'HomeController@home')->name('home');
Route::prefix('home')->group(function () {
    Route::get('berita', 'HomeController@berita')->name('berita');

    Route::group(['middleware' => ['auth', 'client']], function () {
        Route::get('permintaan-pengujian/{id}', 'V1\PermintaanPengujian@create')->name('permintaan.pengujian.create');
        Route::post('permintaan-pengujian/{id}/store', 'V1\PermintaanPengujian@store')->name('permintaan.pengujian.store');
    });

    Route::get('pesertabimtek/certificate', 'PesertaBimtekController@cert')->name('pesertabimtek.cert');

    Route::get('pengajar', 'HomeController@pengajar')->name('pengajar');
    Route::get('pejabat', 'HomeController@pejabat')->name('pejabat');
    Route::get('fasilitas', 'HomeController@fasilitas')->name('fasilitas');
    Route::get('sejarah', 'HomeController@sejarah')->name('sejarah');
    Route::get('visimisi', 'HomeController@visimisi')->name('visimisi');
    Route::get('alur-pelayanan', 'HomeController@alurpelayanan')->name('alurpelayanan');
    Route::get('kebijakan-pelayanan', 'HomeController@kebijakanpelayanan')->name('kebijakan-pelayanan');
    Route::get('struktur', 'HomeController@struktur')->name('struktur');
    Route::get('detailberita/{berita}', 'HomeController@detailberita')->name('detailberita');
    Route::get('tugasfungsi', 'HomeController@tugasfungsi')->name('tugasfungsi');
    Route::get('maklumat', 'HomeController@maklumat')->name('maklumat');
    Route::get('kepuasan_pelanggan', 'HomeController@kepuasan_pelanggan')->name('kepuasan_pelanggan');

    Route::get('pengaduan-masyarakat', 'V1\SettingAppController@form_pengaduan')->name('pengaduan-masyarakat.create');
    Route::post('pengaduan-masyarakat/store', 'V1\SettingAppController@laporan_masyarakat')->name('pengaduan-masyarakat.store');

    Route::get('pelapor-gratifikasi', 'V1\SettingAppController@form_pelaporan')->name('pelapor-gratifikasi.create');
    Route::post('pelapor-gratifikasi/store', 'V1\SettingAppController@pelaporan_grafikasi')->name('pelapor-gratifikasi.store');

    Route::get('pelayanan/tracking', 'HomeController@pelayananTracking')->name('pelayanan.tracking');
    Route::get('pelayanan/advisi-teknis', 'V1\AdvisiTeknisController')->name('home.pelayanan.advisi-teknis');
    Route::get('pelayanan/{id}', 'PelayananController@pelayanan')->name('home.pelayanan.extra');

    Route::get('pelayanan', 'HomeController@pelayanan')->name('pelayanan');

    Route::get('jadwal-pengujian', 'V1\KegiatanController@home')->name('jadwal-pengujian');
    Route::get('jadwal-bimtek', 'V1\JadwalBimtekController@home')->name('jadwal-bimtek');

    // Bimtek
    Route::get('daftar-bimtek/{id}', 'BimtekController@register')->name('bimtek.register');
    Route::post('pesertabimtek', 'PesertaBimtekController@store')->name('pesertabimtek.store');

    Route::get('galeri/{kategori}', 'HomeController@galeri')->name('galeri');
    Route::get('maskot', 'HomeController@maskot')->name('maskot');
    Route::get('cariberita', 'HomeController@cariberita')->name('cariberita');

    Route::get('uji-lab-bahan', function () {
        return view('homepage.uji-lab-bahan');
    })->name('uji.lab.bahan');

    Route::get('uji-lab-struktur', function () {
        return view('homepage.uji-lab-struktur');
    })->name('uji.lab.struktur');

    Route::get('faq', 'HomeController@faq')->name('faq');
    // Bimtek
    Route::get('daftar-bimtek/{id}', 'BimtekController@register')->name('bimtek.register');
    Route::post('pesertabimtek', 'PesertaBimtekController@store')->name('pesertabimtek.store');
});

Route::prefix('admin')->group(function () {

    Route::get('create-bimtek', 'BimtekController@create')->name('bimtek.create');

    Route::resource('berita', 'BeritaController');
    Route::group(['middleware' => ['auth']], function () {
        // Route Berita
        //Route Pelayanan
        Route::get('pelayanan/{kategori}', 'PelayananController@index')->name('pelayanan.index');
        Route::get('pelayanan/{kategori}/create/', 'PelayananController@create')->name('pelayanan.create');
        Route::post('pelayanan/store', 'PelayananController@store')->name('pelayanan.store');
        Route::get('pelayanan/{id}/edit/', 'PelayananController@edit')->name('pelayanan.edit');
        Route::patch('pelayanan/{id}/update', 'PelayananController@update')->name('pelayanan.update');
        Route::delete('pelayanan/{id}', 'PelayananController@destroy')->name('pelayanan.destroy');
        //Route Informasi Publik
        Route::resource('informasipublik', 'InformasiPublikController');
        // Maskot
        Route::resource('maskot', 'MaskotController');
        Route::resource('maklumat', 'MaklumatController');

        Route::resource('beritaui', 'BeritaUIController');
        Route::resource('pelayananui', 'PelayananUIController');
        Route::resource('videoui', 'VideoUIController');

        Route::resource('instansi', 'InstansiController', [
            'as' => 'admin',
        ]);

        Route::group(['prefix' => 'instansi/{instansi}'], function () {
            Route::resource('unit-kerja', 'InstansiUnitKerjaController', [
                'as' => 'admin.instansi',
            ]);
        });

        // BIMTEK
        Route::post('bimtek', 'BimtekController@store')->name('bimtek.store');
        Route::get('bimtek/{id}/edit/', 'BimtekController@edit')->name('bimtek.edit');
        Route::post('bimtek/{id}/update', 'BimtekController@update')->name('bimtek.update');
        Route::delete('bimtek/{id}', 'BimtekController@destroy')->name('bimtek.destroy');
        Route::get('pesertabimtek/{bimtek}', 'PesertaBimtekController@index')->name('pesertabimtek.index');
        Route::get('pesertabimtek/{id}/edit/', 'PesertaBimtekController@edit')->name('pesertabimtek.edit');
        Route::post('pesertabimtek/{id}/update/', 'PesertaBimtekController@update')->name('pesertabimtek.update');
        Route::delete('pesertabimtek/{id}', 'PesertaBimtekController@destroy')->name('pesertabimtek.destroy');

        // EXPORT
        Route::get('pegawai/export', 'ExportController@pegawai')->name('pegawai.export');
        Route::get('bimtek-peserta/export', 'ExportController@bimtek_peserta')->name('bimtek-peserta.export');
        Route::get('client/export', 'ExportController@client')->name('client.export');
        Route::get('permintaan-pengujian/export', 'ExportController@permintaan_pengujian')->name('admin.permintaan.export');
        Route::get('struktur-organisasi/export', 'ExportController@struktur_organisasi')->name('struktur-organisasi.export');
        Route::get('jadwal-pengujian/export', 'ExportController@jadwal_pengujian')->name('jadwal-pengujian.export');
        Route::get('jadwal-bimtek/export', 'ExportController@jadwal_bimtek')->name('jadwal-bimtek.export');
        Route::get('umpan-balik/export', 'ExportController@umpan_balik')->name('umpan-balik.export');
        Route::get('kepuasan-pelanggan/export', 'ExportController@kepuasan_pelanggan')->name('kepuasan-pelanggan.export');
        Route::get('indeks-kepuasan/export', 'ExportController@indeks_kepuasan')->name('indeks-kepuasan.export');
        Route::get('akun/export', 'ExportController@akun')->name('akun.export');
        Route::get('pelayanan/{kategori}/export', 'ExportController@pelayanan')->name('pelayanan.export');
        Route::get('peralatan-lab/export', 'ExportController@peralatan_lab')->name('peralatan-lab.export');
        Route::get('jadwal-kegiatan-personil/export', 'ExportController@jadwal-kegiatan-personil')
        ->name('jadwal-kegaiatan-personil.export');


        // IMPORT
        Route::post('pegawai/import', 'ImportController@pegawai')->name('pegawai.import');
        Route::get('pegawai/import.template', function () {
            return response()->download('excel_default/Template Import Data Peralatan.xlsx');
        })->name('pegawai.import.template');
        Route::post('peralatan/import', 'ImportController@peralatan')->name('peralatan.import');
        Route::post('struktur-organisasi/export', 'ImportController@struktur_organisasi')->name('struktur-organisasi.import');
        Route::post('pelayanan/{kategori}/import', 'ImportController@pelayanan')->name('pelayanan.import');
        Route::get('contoh-import-excel', function () {
            return response()->download('excel_default/contoh_import_new.xlsx');
        })->name('contoh-excel');

        //Advisi Teknis
        Route::get('old-advisi-teknis/{status}/detail', 'V1\Admin\AdvisiTeknisController@oldIndex')->name('advisiteknis.index');

        Route::get(
            'advisi-teknis/{advisiTeknis}/kuisioner',
            'V1\Admin\AdvisTeknisKuisionerController@index'
        )
        ->name('admin.advisi-teknis.kuisioner');
        Route::post(

resources/views/admin/beritaui-p/edit.blade.php
@extends('layouts.adminlte')
@section('main')
@include('admin.parts.breadcrumbs', [
    'judul' => [
        [
            'judul' => 'Berita', 
            'link' => 'berita.index',
        ],
        [
            'judul' => 'Simpan Data Berita',
        ]
]])
<div class="container">
@if (session()->has('success'))
<div class="alert alert-success" role="alert">
    {{ session()->get('success') }}
</div>
@endif
@if (session()->has('failed'))
    <div class="alert alert-danger" role="alert">
        {{ session()->get('failed') }}
    </div>
@endif
    <div class="card">
        <div class="card-header bg-biru text-white">
            <h3>Ubah Tampilan Menu Berita di Beranda</h3>
        </div>
        <form action="{{route('beritaui.update', $beritaUI->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('patch')
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="form-group">
                            <label for="jumlah_berita">Jumlah</label>
                            <input type="number" value="{{$beritaUI->jumlah_berita}}" max="{{$berita->count()}}" min="1" name="jumlah_berita" id="jumlah_berita" class="form-control @error('jumlah_berita') is-invalid @enderror">
                            @error('jumlah_berita')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="berita_1_id">Panel Berita 1</label>
                            <select name="berita_1_id" id="berita_1_id" class="custom-select custom-select-sm">
                                <option value="">Pilih Berita</option>
                                <option value="0" @if($beritaUI->berita_1_id == 0) selected @endif>Acak</option>
                                @foreach ($berita as $item)
                                    <option value="{{$item->id}}" @if($item->id == $beritaUI->berita_1_id) selected @endif>{{$item->judul}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="berita_2_id">Panel Berita 2</label>
                            <select name="berita_2_id" id="berita_2_id" class="custom-select custom-select-sm">
                                <option value="">Pilih Berita</option>
                                <option value="0" @if($beritaUI->berita_2_id == 0) selected @endif>Acak</option>
                                @foreach ($berita as $item)
                                    <option value="{{$item->id}}" @if($item->id == $beritaUI->berita_2_id) selected @endif>{{$item->judul}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="berita_3_id">Panel Berita 3</label>
                            <select name="berita_3_id" id="berita_3_id" class="custom-select custom-select-sm">
                                <option value="">Pilih Berita</option>
                                <option value="0" @if($beritaUI->berita_3_id == 0) selected @endif>Acak</option>
                                @foreach ($berita as $item)
                                    <option value="{{$item->id}}" @if($item->id == $beritaUI->berita_3_id) selected @endif>{{$item->judul}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="berita_4_id">Panel Berita 4</label>
                            <select name="berita_4_id" id="berita_4_id" class="custom-select custom-select-sm">
                                <option value="">Pilih Berita</option>
                                <option value="0" @if($beritaUI->berita_4_id == 0) selected @endif>Acak</option>
                                @foreach ($berita as $item)
                                    <option value="{{$item->id}}" @if($item->id == $beritaUI->berita_4_id) selected @endif>{{$item->judul}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                
                
                
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Simpan</button>
            </div>
        </form>
    </div>
</div>
@endsection